# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build Jar

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Publish

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'zulu'
    - name: Build Jar
      uses: gradle/gradle-build-action@cfc50b189af149aeb55f94103f47753382d88d33
      with:
        arguments: shadowJar
    - name: Upload Jar
      uses: actions/upload-artifact@v3.1.1
      with:
        name: Fat Jar
        path: build/libs/*-all.jar
    - name: Publish
      uses: gradle/gradle-build-action@cfc50b189af149aeb55f94103f47753382d88d33
      with:
        arguments: publish
      env:
        TOKEN: ${{ secrets.TOKEN }}
